### ISSUE TITLE
Pixi.js 3 Compatibility

### ISSUE THREAD

**Issue by mjhasbach** [alforno-productions/HexPixiJs#5]
There are a few issues when attempting to use this library with Pixi.js 3.0.2:

`ReferenceError: The loader system was overhauled in pixi v3, please see the new PIXI.loaders.Loader class.`

`"You do not need to use a PIXI Stage any more, you can simply render any container."`

`"DisplayObjectContainer has been shortened to Container, please use Container from now on."`

**Comment by mark-harmon** [comment]
I'll check it out. Sorry for the late reply.

**Comment by Hachitus** [comment]
@alforno-productions I made a small fork, with changes needed for simpleDemo (one). https://github.com/Hachitus/HexPixiJs

Not sure what's the thing with requestAnimFrame, but I used the window.requestAnimationFrame as the PIXI equivalent was not available for me. I used cloudflare cdn for PIXI script, so that can be set to local file. Also I didn't fix simpleDemo2 yet anyway.

Otherwise should be fine.

Might fix them later and inform, when I have the time too, but that should at least make things easier to update if nothing else :)
